package config

import (
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestBeeConfig_Defaults(t *testing.T) {
	cases := []struct {
		name  string
		yaml  string
		check func(t *testing.T, cfg BeeConfig)
	}{
		{
			name: "DerivedFields",
			yaml: `
server:
  host: "localhost"
  port: 8080
bee:
  engines:
    claude:
      path: "claude-custom"
`,
			check: func(t *testing.T, cfg BeeConfig) {
				assert.Equal(t, "http://localhost:8080", cfg.RPCBaseURL)
				assert.Equal(t, "claude-custom", cfg.Engines.Claude.Path)
			},
		},
		{
			name: "BinaryDefault",
			yaml: `
server:
  host: "localhost"
  port: 8080
`,
			check: func(t *testing.T, cfg BeeConfig) {
				assert.Equal(t, "claude", cfg.Engines.Claude.Path)
			},
		},
		{
			name: "TelegramDefaults",
			yaml: `
server:
  port: 8080
`,
			check: func(t *testing.T, cfg BeeConfig) {
				assert.Equal(t, 50*1024*1024, cfg.Platforms.Telegram.MaxMediaSize)
			},
		},
		{
			name: "TokenSecretAutoGenerated",
			yaml: `
server:
  port: 8080
`,
			check: func(t *testing.T, cfg BeeConfig) {
				assert.NotEmpty(t, cfg.RPC.TokenSecret, "TokenSecret should be auto-generated when not set")
			},
		},
		{
			name: "LinearDefaults",
			yaml: `
server:
  port: 8080
`,
			check: func(t *testing.T, cfg BeeConfig) {
				assert.Equal(t, 50*1024*1024, cfg.Platforms.Linear.MaxMediaSize)
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			f, _ := os.CreateTemp("", "*.yaml")
			f.WriteString(tc.yaml)
			f.Close()
			defer os.Remove(f.Name())

			cfg, err := Load(f.Name())
			require.NoError(t, err)
			tc.check(t, cfg.Bee)
		})
	}
}

func TestBeeConfig_EngineTimeoutSplitDefaults(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  name: "bee"
`)
	f.Close()

	cfg, err := Load(f.Name())
	require.NoError(t, err)

	assert.Equal(t, 5*time.Minute, cfg.Bee.Engine.Timeout.Bee)
	assert.Equal(t, 30*time.Minute, cfg.Bee.Engine.Timeout.Worker)
}

func TestBeeConfig_TelegramLoad(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  platforms:
    telegram:
      enabled: true
      token: "test-token"
      max_media_size: 10485760
`)
	f.Close()

	cfg, err := Load(f.Name())
	require.NoError(t, err)

	tc := cfg.Bee.Platforms.Telegram
	assert.True(t, tc.Enabled)
	assert.Equal(t, "test-token", tc.Token)
	assert.Equal(t, 10485760, tc.MaxMediaSize)
}

func TestGetLang_fromFile(t *testing.T) {
	f, err := os.CreateTemp("", "*.yaml")
	require.NoError(t, err)
	f.WriteString(`language: en`)
	f.Close()
	defer os.Remove(f.Name())

	got := GetLang(f.Name())
	assert.Equal(t, "en", got)
}

func TestGetLang_missing(t *testing.T) {
	got := GetLang("/nonexistent/path.yaml")
	assert.Empty(t, got)
}

func TestGetLang_notSet(t *testing.T) {
	f, err := os.CreateTemp("", "*.yaml")
	require.NoError(t, err)
	f.WriteString(`server:
  port: 8080`)
	f.Close()
	defer os.Remove(f.Name())

	got := GetLang(f.Name())
	assert.Empty(t, got)
}

func TestBeeConfig_TokenTTLDefault(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`server:
  port: 8080`)
	f.Close()
	defer os.Remove(f.Name())

	cfg, err := Load(f.Name())
	require.NoError(t, err)
	assert.Equal(t, 48*time.Hour, cfg.Bee.RPC.TokenTTL)
}

func TestBeeConfig_TokenSecretAndTTLExplicit(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  rpc:
    token_secret: "my-secret"
    token_ttl: 4h
`)
	f.Close()
	defer os.Remove(f.Name())

	cfg, err := Load(f.Name())
	require.NoError(t, err)
	assert.Equal(t, "my-secret", cfg.Bee.RPC.TokenSecret)
	assert.Equal(t, 4*time.Hour, cfg.Bee.RPC.TokenTTL)
}

func TestEngineItemConfig_EnvField(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  engines:
    claude:
      path: claude
      env:
        ANTHROPIC_BASE_URL: https://proxy.example.com
        CUSTOM_KEY: "value with spaces"
    pi:
      path: pi
      env:
        PI_VAR: pi_value
    codex:
      path: codex
`)
	f.Close()
	defer os.Remove(f.Name())

	cfg, err := Load(f.Name())
	require.NoError(t, err)

	assert.Equal(t, "https://proxy.example.com", cfg.Bee.Engines.Claude.Env["ANTHROPIC_BASE_URL"])
	assert.Equal(t, "value with spaces", cfg.Bee.Engines.Claude.Env["CUSTOM_KEY"])
	assert.Equal(t, "pi_value", cfg.Bee.Engines.Pi.Env["PI_VAR"])
	assert.Nil(t, cfg.Bee.Engines.Codex.Env)
}

func TestBeeConfig_LinearLoad(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  platforms:
    linear:
      enabled: true
      api_key: "lin_test"
      max_media_size: 10485760
`)
	f.Close()

	cfg, err := Load(f.Name())
	require.NoError(t, err)
	lc := cfg.Bee.Platforms.Linear
	assert.True(t, lc.Enabled)
	assert.Equal(t, "lin_test", lc.APIKey)
	assert.Equal(t, 10485760, lc.MaxMediaSize)
}

func TestEngineConfigRawFor_IncludesEnv(t *testing.T) {
	f, _ := os.CreateTemp("", "*.yaml")
	f.WriteString(`
server:
  port: 8080
bee:
  engines:
    claude:
      path: my-claude
      env:
        MY_KEY: my_value
    codex:
      path: codex
`)
	f.Close()
	defer os.Remove(f.Name())

	cfg, err := Load(f.Name())
	require.NoError(t, err)

	raw := cfg.Bee.EngineConfigRawFor("claude")
	require.NotNil(t, raw)
	got, _ := raw["path"].(string)
	assert.Equal(t, "my-claude", got)
	env, _ := raw["env"].(map[string]string)
	assert.Equal(t, "my_value", env["MY_KEY"])

	// Engine with no env — raw["env"] must still be present (nil is fine for type assertion)
	rawCodex := cfg.Bee.EngineConfigRawFor("codex")
	require.NotNil(t, rawCodex)
	envCodex, _ := rawCodex["env"].(map[string]string)
	assert.Empty(t, envCodex)
}
