// Package toolnames defines MCP tool name constants as the single source of truth.
package utils

const (
	ListWorkers          = "list_workers"
	GetWorker            = "get_worker"
	CreateWorker         = "create_worker"
	UpdateWorker         = "update_worker"
	DeleteWorker         = "delete_worker"
	CreateTask           = "create_task"
	ListTasks            = "list_tasks"
	CancelTask           = "cancel_task"
	SendMessage          = "send_message"
	ClearSession         = "clear_session"
	GetWorkerStatus      = "get_worker_status"
	GetSystemOverview    = "get_system_overview"
	ListBeeExecutions    = "list_bee_executions"
	SaveConstraint       = "save_constraint"
	GetConstraint        = "get_constraint"
	DeleteConstraint     = "delete_constraint"
	ListSessionContexts  = "list_session_contexts"
	ClearWorkerSession   = "clear_worker_session"
	ListDepartments      = "list_departments"
	GetDepartment        = "get_department"
	CreateDepartment     = "create_department"
	UpdateDepartment     = "update_department"
	DeleteDepartment     = "delete_department"
	ListMessages         = "list_messages"
	ListOutboundMessages = "list_outbound_messages"
	ListExecutions       = "list_executions"
)
